CREATE DATABASE tasks;

CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    dateofcreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dueDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dateCompleted TIMESTAMP DEFAULT NULL
);